### ISSUE TITLE
macOS M1 - ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by truediogo** [nonra/find-the-peacock#1]
I got these error when i try to compile in macOS Ventura 13.1 with M1 processor 

`Undefined symbols for architecture arm64:
  "_BeginDrawing", referenced from:
      _main in main-1069bb.o
  "_CheckCollisionPointRec", referenced from:
      _main in main-1069bb.o
  "_ClearBackground", referenced from:
      _main in main-1069bb.o
  "_CloseAudioDevice", referenced from:
      _main in main-1069bb.o
  "_CloseWindow", referenced from:
      _main in main-1069bb.o
  "_EndDrawing", referenced from:
      _main in main-1069bb.o
  "_GetCharPressed", referenced from:
      _main in main-1069bb.o
  "_GetMousePosition", referenced from:
      _main in main-1069bb.o
  "_GetRandomValue", referenced from:
      _main in main-1069bb.o
  "_GetTime", referenced from:
      _main in main-1069bb.o
  "_InitAudioDevice", referenced from:
      _main in main-1069bb.o
  "_InitWindow", referenced from:
      _main in main-1069bb.o
  "_IsKeyDown", referenced from:
      _main in main-1069bb.o
  "_IsKeyPressed", referenced from:
      _main in main-1069bb.o
  "_LoadSound", referenced from:
      _main in main-1069bb.o
  "_LoadTexture", referenced from:
      _main in main-1069bb.o
  "_PlaySoundMulti", referenced from:
      _main in main-1069bb.o
  "_SetMouseCursor", referenced from:
      _main in main-1069bb.o
  "_SetSoundVolume", referenced from:
      _main in main-1069bb.o
  "_SetTargetFPS", referenced from:
      _main in main-1069bb.o
  "_StopSound", referenced from:
      _main in main-1069bb.o
  "_StopSoundMulti", referenced from:
      _main in main-1069bb.o
  "_UnloadSound", referenced from:
      _main in main-1069bb.o
  "_WindowShouldClose", referenced from:
      _main in main-1069bb.o
  "_clockView", referenced from:
      _main in main-1069bb.o
  "_createMaze", referenced from:
      _main in main-1069bb.o
  "_createUser", referenced from:
      _main in main-1069bb.o
  "_gameView", referenced from:
      _main in main-1069bb.o
  "_getOrdenaredUsersByTime", referenced from:
      _main in main-1069bb.o
  "_getUser", referenced from:
      _main in main-1069bb.o
  "_initialView", referenced from:
      _main in main-1069bb.o
  "_scoreAndRankingView", referenced from:
      _main in main-1069bb.o
  "_updateUser", referenced from:
      _main in main-1069bb.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`
